Remove unused test jobs from GitHub Actions workflow
Removed multiple C++ and Python test jobs from the GitHub Actions workflow, including configurations for ARM64, macOS, and Windows platforms. Updated the workflow to only include the C++ tests for Linux x64 and a dispatch trigger.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,11 +1,7 @@
 name: Test
 
 on:
-  push:
-    branches:
-      - develop
-      - master
-  pull_request:
+  workflow_dispatch: 
 
 jobs:
   cpp-linux-x64:
@@ -16,9 +12,9 @@ jobs:
       matrix:
         build_type:
           - Debug
-          - Release
+          # - Release
         compiler:
-          - clang
+          # - clang
           - gcc
     steps:
       - name: Checkout
@@ -34,270 +30,270 @@ jobs:
           conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-x64
           shell: bash
 
-  cpp-linux-arm64:
-    name: "C++ tests (gcc/Linux/ARM64)"
-    runs-on: ubuntu-24.04-arm
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          - Debug
-          - Release
-        compiler:
-          - clang
-          - gcc
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install libc++
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libc++-dev libc++abi-dev
-      - uses: ./.github/actions/cpp-tests
-        with:
-          build_type: ${{ matrix.build_type }}
-          conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-arm64
-          conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-arm64
-          shell: bash
+  # cpp-linux-arm64:
+  #   name: "C++ tests (gcc/Linux/ARM64)"
+  #   runs-on: ubuntu-24.04-arm
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         - Debug
+  #         - Release
+  #       compiler:
+  #         - clang
+  #         - gcc
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install libc++
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install -y libc++-dev libc++abi-dev
+  #     - uses: ./.github/actions/cpp-tests
+  #       with:
+  #         build_type: ${{ matrix.build_type }}
+  #         conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-arm64
+  #         conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-${{ matrix.compiler }}-linux-arm64
+  #         shell: bash
 
-  cpp-macos-x64:
-    name: "C++ tests (clang/MacOS/x64)"
-    runs-on: macos-15-intel  # x64
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          - Debug
-          - Release
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/cpp-tests
-        with:
-          build_type: ${{ matrix.build_type }}
-          conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-x64
-          conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-x64
-          shell: bash
+  # cpp-macos-x64:
+  #   name: "C++ tests (clang/MacOS/x64)"
+  #   runs-on: macos-15-intel  # x64
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: ./.github/actions/cpp-tests
+  #       with:
+  #         build_type: ${{ matrix.build_type }}
+  #         conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-x64
+  #         conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-x64
+  #         shell: bash
 
-  cpp-macos-arm64:
-    name: "C++ tests (clang/macos/ARM64)"
-    runs-on: macos-14  # ARM4
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          - Debug
-          - Release
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/cpp-tests
-        with:
-          build_type: ${{ matrix.build_type }}
-          conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-arm64
-          conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-arm64
-          shell: bash
+  # cpp-macos-arm64:
+  #   name: "C++ tests (clang/macos/ARM64)"
+  #   runs-on: macos-14  # ARM4
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: ./.github/actions/cpp-tests
+  #       with:
+  #         build_type: ${{ matrix.build_type }}
+  #         conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-arm64
+  #         conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-apple_clang-macos-arm64
+  #         shell: bash
 
-  cpp-windows-x64:
-    name: "C++ tests (msvc/Windows/x64)"
-    runs-on: windows-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          # Disabled temporarily.
-          # Until an antlr4-cppruntime>4.13.1 Conan package builds in Windows/Debug
-          # - Debug
-          - Release
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/cpp-tests
-        with:
-          build_type: ${{ matrix.build_type }}
-          conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-msvc-windows-x64
-          conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-msvc-windows-x64
-          shell: bash
+  # cpp-windows-x64:
+  #   name: "C++ tests (msvc/Windows/x64)"
+  #   runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         # Disabled temporarily.
+  #         # Until an antlr4-cppruntime>4.13.1 Conan package builds in Windows/Debug
+  #         # - Debug
+  #         - Release
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: ./.github/actions/cpp-tests
+  #       with:
+  #         build_type: ${{ matrix.build_type }}
+  #         conan_profile_host: conan/profiles/tests-${{ matrix.build_type }}-msvc-windows-x64
+  #         conan_profile_build: conan/profiles/tests-${{ matrix.build_type }}-msvc-windows-x64
+  #         shell: bash
 
-  cpp-shared:
-    name: "C++ tests (shared)"
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          - Debug
-          - Release
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/cpp-tests
-        with:
-          build_type: ${{ matrix.build_type }}
-          conan_profile_host: conan/profiles/${{ matrix.build_type }}-gcc-linux-x64-shared
-          conan_profile_build: conan/profiles/${{ matrix.build_type }}-gcc-linux-x64-shared
-          shell: bash
+  # cpp-shared:
+  #   name: "C++ tests (shared)"
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: ./.github/actions/cpp-tests
+  #       with:
+  #         build_type: ${{ matrix.build_type }}
+  #         conan_profile_host: conan/profiles/${{ matrix.build_type }}-gcc-linux-x64-shared
+  #         conan_profile_build: conan/profiles/${{ matrix.build_type }}-gcc-linux-x64-shared
+  #         shell: bash
 
-  ts-emscripten-wasm:
-    name: "TS tests (clang/emscripten/wasm)"
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build_type:
-          - Release
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 16.20.2
-      - name: Install conan
-        run: |
-          pipx install conan
-        shell: bash
-      - name: Get latest CMake
-        uses: lukka/get-cmake@latest
-        # We clean the Conan cache as a preventive measure for our runs in self-hosted runners
-        # Self-hosted runners use containers that cache Conan packages from previous runs,
-        # and that can cause different type of problems
-      - name: Configure and build
-        run: |
-          conan profile detect --force
-          conan remove -c "*/*"
-          conan build . -pr=conan/profiles/release-clang-emscripten-wasm -pr:b=conan/profiles/release -b missing
-        shell: bash
-      - name: Rename cqasm_emscripten.js to cqasm_emscripten.mjs
-        working-directory: build/Release/emscripten
-        run: |
-          mv cqasm_emscripten.js cqasm_emscripten.mjs
-        shell: bash
-      - name: Install deno
-        uses: denoland/setup-deno@v1
-        with:
-          deno-version: v1.x
-      - name: Test
-        working-directory: emscripten
-        run: |
-          deno run -A test_libqasm.ts
-        shell: bash
+  # ts-emscripten-wasm:
+  #   name: "TS tests (clang/emscripten/wasm)"
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build_type:
+  #         - Release
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 16.20.2
+  #     - name: Install conan
+  #       run: |
+  #         pipx install conan
+  #       shell: bash
+  #     - name: Get latest CMake
+  #       uses: lukka/get-cmake@latest
+  #       # We clean the Conan cache as a preventive measure for our runs in self-hosted runners
+  #       # Self-hosted runners use containers that cache Conan packages from previous runs,
+  #       # and that can cause different type of problems
+  #     - name: Configure and build
+  #       run: |
+  #         conan profile detect --force
+  #         conan remove -c "*/*"
+  #         conan build . -pr=conan/profiles/release-clang-emscripten-wasm -pr:b=conan/profiles/release -b missing
+  #       shell: bash
+  #     - name: Rename cqasm_emscripten.js to cqasm_emscripten.mjs
+  #       working-directory: build/Release/emscripten
+  #       run: |
+  #         mv cqasm_emscripten.js cqasm_emscripten.mjs
+  #       shell: bash
+  #     - name: Install deno
+  #       uses: denoland/setup-deno@v1
+  #       with:
+  #         deno-version: v1.x
+  #     - name: Test
+  #       working-directory: emscripten
+  #       run: |
+  #         deno run -A test_libqasm.ts
+  #       shell: bash
 
-  python-linux-x64:
-    name: "Python tests (Linux/x64)"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install SWIG
-        run: |
-          sudo apt-get install -y swig
-        shell: bash
-      - uses: ./.github/actions/python-tests
-        with:
-          shell: bash
+  # python-linux-x64:
+  #   name: "Python tests (Linux/x64)"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install SWIG
+  #       run: |
+  #         sudo apt-get install -y swig
+  #       shell: bash
+  #     - uses: ./.github/actions/python-tests
+  #       with:
+  #         shell: bash
 
-  python-linux-arm64:
-    name: "Python tests (Linux/arm64)"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install SWIG
-        run: |
-          sudo apt-get install -y swig
-        shell: bash
-      - uses: ./.github/actions/python-tests
-        with:
-          shell: bash
+  # python-linux-arm64:
+  #   name: "Python tests (Linux/arm64)"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install SWIG
+  #       run: |
+  #         sudo apt-get install -y swig
+  #       shell: bash
+  #     - uses: ./.github/actions/python-tests
+  #       with:
+  #         shell: bash
 
-  python-macos-x64:
-    name: "Python tests (macOS/x64)"
-    runs-on: macos-15-intel
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install SWIG
-        run: |
-          brew install swig
-        shell: bash
-      - uses: ./.github/actions/python-tests
-        with:
-          shell: bash
+  # python-macos-x64:
+  #   name: "Python tests (macOS/x64)"
+  #   runs-on: macos-15-intel
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install SWIG
+  #       run: |
+  #         brew install swig
+  #       shell: bash
+  #     - uses: ./.github/actions/python-tests
+  #       with:
+  #         shell: bash
 
-  python-macos-arm64:
-    name: "Python tests (macOS/arm64)"
-    runs-on: macos-14
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install SWIG
-        run: |
-          brew install swig
-        shell: bash
-      - uses: ./.github/actions/python-tests
-        with:
-          shell: bash
+  # python-macos-arm64:
+  #   name: "Python tests (macOS/arm64)"
+  #   runs-on: macos-14
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install SWIG
+  #       run: |
+  #         brew install swig
+  #       shell: bash
+  #     - uses: ./.github/actions/python-tests
+  #       with:
+  #         shell: bash
 
-  python-windows-x64:
-    name: "Python tests (Windows/x64)"
-    runs-on: windows-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/python-tests
-        with:
-          shell: bash
+  # python-windows-x64:
+  #   name: "Python tests (Windows/x64)"
+  #   runs-on: windows-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - uses: ./.github/actions/python-tests
+  #       with:
+  #         shell: bash
 
-  docker:
-    name: Docker
-    runs-on: ubuntu-latest
-    steps:
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Build without pushing
-        uses: docker/build-push-action@v5
-        with:
-          push: false
-          tags: libqasm:latest
+  # docker:
+  #   name: Docker
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #     - name: Build without pushing
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         push: false
+  #         tags: libqasm:latest
 
-  complete:
-    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
-    name: Report status
-    needs:
-      - cpp-linux-x64
-      - cpp-linux-arm64
-      - cpp-macos-x64
-      - cpp-macos-arm64
-      - cpp-windows-x64
-      - cpp-shared
-      - ts-emscripten-wasm
-      - python-linux-x64
-      - python-linux-arm64
-      - python-macos-x64
-      - python-macos-arm64
-      - python-windows-x64
-      - docker
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check all job status
-        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
-        # see https://stackoverflow.com/a/67532120/4907315
-        if: >-
-          ${{
-               contains(needs.*.result, 'failure')
-            || contains(needs.*.result, 'cancelled')
-            || (
-                    github.ref != 'refs/heads/develop'
-                 && contains(needs.*.result, 'skipped')
-               )
-            ||
-               (
-                    github.ref == 'refs/heads/develop'
-                 && contains(needs.*.result, 'skipped')
-               )
-          }}
-        run: exit 1
+  # complete:
+  #   # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
+  #   name: Report status
+  #   needs:
+  #     - cpp-linux-x64
+  #     - cpp-linux-arm64
+  #     - cpp-macos-x64
+  #     - cpp-macos-arm64
+  #     - cpp-windows-x64
+  #     - cpp-shared
+  #     - ts-emscripten-wasm
+  #     - python-linux-x64
+  #     - python-linux-arm64
+  #     - python-macos-x64
+  #     - python-macos-arm64
+  #     - python-windows-x64
+  #     - docker
+  #   if: ${{ always() }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check all job status
+  #       # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
+  #       # see https://stackoverflow.com/a/67532120/4907315
+  #       if: >-
+  #         ${{
+  #              contains(needs.*.result, 'failure')
+  #           || contains(needs.*.result, 'cancelled')
+  #           || (
+  #                   github.ref != 'refs/heads/develop'
+  #                && contains(needs.*.result, 'skipped')
+  #              )
+  #           ||
+  #              (
+  #                   github.ref == 'refs/heads/develop'
+  #                && contains(needs.*.result, 'skipped')
+  #              )
+  #         }}
+  #       run: exit 1
